Aburgaya/urls.py
import os

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from Aburgaya import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    path('products/', include("Products.urls")),
    # path('authors/', include("Company.urls")),
    # path('publisher/', include("Publishers.urls")),
    path('category/', include("Categories.urls")),
    path('accounts/', include("Accounts.urls")),
    path('company/', include("Company.urls")),
    path('manage/', include("Manager.urls")),


    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': os.path.join(settings.MEDIA_ROOT)}, name="media"),
]

Company/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'Company'
urlpatterns = [
    path('', AuthorsListView.as_view(), name='home'),
    path('<int:pk>/detail', AuthorsDetailView.as_view(), name='detail'),
    path('add', login_required(AddAuthorsView.as_view()), name='add'),
    path('<int:pk>/edit', login_required(EditAuthorsView.as_view()), name='edit'),
    path('<int:pk>/delete', login_required(DeleteAuthorsView.as_view()), name='delete'),
]

Home/urls.py
from django.urls import path

from Home.views import *


app_name = "Home"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('library', LibraryView.as_view(), name='library'),
    path('setlang=<str:lang>', LanguageView.as_view(), name="setLanguage"),
    path('about', AboutView.as_view(), name="about"),
]

Products/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from Products.views import *

app_name = "Products"
urlpatterns = [
    path('', ProductsListView.as_view(), name='home'),
    path('<int:pk>/detail', ProductDetailView.as_view(), name='detail'),
    path('add', login_required(AddProductView.as_view()), name='add'),
    path('<int:pk>/edit', login_required(ProductEditView.as_view()), name='edit'),
    path('<int:pk>/delete', login_required(ProductDeleteView.as_view()), name='delete'),
    # path('list', ProductsListView.as_view(), name='list'),
]

Summaries/urls.py
from django.urls import path
from .views import *

app_name= 'Summaries'
urlpatterns = [
    path('', SummariesListView.as_view(), name='home'),
    path('<int:pk>/detail', SummariesDetailView.as_view(), name='detail'),
    path('add', SummariesAddView.as_view(), name='add'),
    path('<int:pk>/edit', SummariesEditView.as_view(), name='edit'),
    path('<int:pk>/delete', SummariesDeleteView.as_view(), name='delete'),
]

Home/models.py
from django.db import models

# Create your models here.

Home/forms.py
from Categories.models import Category
from django import forms

class ContactForm(forms.Form):
    email = forms.CharField(max_length=200)
    name = forms.CharField(max_length=2048)
    description = forms.CharField(max_length=2048*10, widget=forms.Textarea())
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all())
    

    email.widget.attrs = {
        'class': 'form-control',
        'placeholder': 'Email',
    }

    name.widget.attrs = {
        'class': 'form-control',
        'placeholder': 'Name',
    }

    description.widget.attrs = {
        'class': 'form-control',
        'placeholder': '...',
        'rows':5
    }

    category.widget.attrs = {
        'class': 'form-control',
        'placeholder': '...',
    }
    
    def clean(self):
        data = super().clean()
        if 'password' in self.data.keys():
            pwd = self.data['password']

            data['is_staff'] = True
            data['is_active'] = True
            # data['date_joined'] = time.time()
            # data['password'] = make_password(pwd)

        # else:
        #     if self.instance.id:
        #         data['password'] = self.instance.password
        #         data['password2'] = self.instance.password
        return super().clean()

    def clean_password(self):
        data = self.cleaned_data
        if not self.instance.id:
            pwd = self.data['password']
            pwd1 = self.data['password2']

            if not (pwd == pwd1 and len(pwd) >= 6):
                raise forms.ValidationError("Please enter valid password.")

        return data

    def save(self, commit=True):
        # self.cleaned_data['date_joined'] = time.time()
        return super().save(commit)

Home/views.py
from django.urls import reverse
from django.utils.translation import activate
from django.views.generic import TemplateView, ListView, RedirectView, FormView
from .forms import ContactForm
from Company.models import Company
from Products.models import Product
from Categories.models import Category
from django.core.mail import send_mail

class HomeView(TemplateView):
    template_name = "home.html"
    extra_context = {
        'products': Product.objects.all()[:4],
        # 'companies': Company.objects.all()[:8],
    }


class LibraryView(ListView):
    template_name = "library.html"
    model = Product
    paginate_by = 20
    context_object_name = "products"
    extra_context = {
        'products': Product.objects.all()[:8],
        'companies': Company.objects.all()[:8],
    }


class LanguageView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        if 'lang' in kwargs.keys():
            lang = kwargs['lang']
            activate(lang)

        data = self.request.GET
        if 'next' in data.keys():
            return data['next']

        return reverse("Home:home")



class AboutView(FormView):
    template_name = "about.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        data = form.cleaned_data
        email = data["email"]
        name = data["name"]
        description = data["description"]
        category = data["category"]
        send_mail(
    '${name}',
    '${description}',
    '${email}',
    ['support@aburgayagroup.com'],
    fail_silently=False,
)

        # if user is None:
        #     return super().form_invalid(form)
        # login(self.request, user)

        return super().form_valid(form)
    

templates/abstruct_header_footer.html
{% load static %}
{% load fullurl %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% fullstatic 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% fullstatic 'css/style.css' %}">
    <link rel="stylesheet" href="{% fullstatic 'css/styler.css' %}">
    <link rel="stylesheet" href="{% fullstatic 'css/admin_style.css' %}">
    <link rel="stylesheet" href="{% fullstatic 'css/fontawesome-all.min.css' %}">
    <title>{% block title %}Aburgaya Group{% endblock %}</title>
    <link rel="shortcut icon" href="{% fullstatic 'imgs/logo-white.svg' %}"/>
</head>
<body >
<div class="container bg-light rounded pb-4">
    <nav class="navbar navbar-expand-lg bg-light" >
        <button class="navbar-toggler mx-3 my-2" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span>
        </button>
    
        <div class="collapse navbar-collapse mx-3" id="navbarTogglerDemo03">
            <div class="text-light mr-3">
                <a class="btn text-light" href="{% url 'Home:home' %}">
                    <img class="" height="50" src="{% static 'imgs/logo-02.svg' %}" alt="">
                    
                </a>
            </div>
    
            <ul class="navbar-nav  mt-2 mt-lg-0  text-primary">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Home:home' %}">{% trans 'Home' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Home:library' %}">{% trans 'Products' %}</a>
                </li>
                <li class="nav-item cm-dropdown">
                    <a href="{% url 'Company:home' %}" class="nav-link">
                        {% trans 'Companies' %}
                    </a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'Home:about' %}">{% trans 'Contact' %}</a>
                </li>
                
            </ul>
    
    
    
        <ul class="navbar-nav ml-auto">
    
            <li class="nav-item dropdown">
                <a class="nav-link text-primary" href="#" id="navbarDropdownMenuLink"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-globe"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'Home:setLanguage' 'ar' %}">{% trans 'Arabic' %}</a>
                    <a class="dropdown-item" href="{% url 'Home:setLanguage' 'en' %}">{% trans 'English' %}</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" id="adminDropMenu" class="nav-link  text-primary"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="adminDropMenu">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% fullurl 'Manager:manager_home' %}">{% trans 'User Page' %}</a>
                        <a class="dropdown-item" href="{% fullurl 'Accounts:logout' %}">{% trans 'Logout' %}</a>
                    {% else %}
                        <a class="dropdown-item" href="{% fullurl 'Accounts:login' %}">{% trans 'Login' %}</a>
                    {% endif %}
                </div>
            </li>
        </ul>
        </div>
    </nav>
    
    
    <div class="full-body">
    
        {% block full_body %}
        {% endblock %}
    
    </div>
    
    
</div>
<div class="container-fluid">
    <div class="footer text-center row">
        
        <div class="container">
            <div class="row w-100" style="">

                <div class="col-2 text-center">
                    <a href="https://muwaija.com/" target="_blank" class="btn text-white">
                    Design by
                        <img class="img-fluid" src="{% static 'imgs/logo_w.png' %}" alt="">
                    </a>
                </div>
                <div class="col"></div>
                <div class="col-3">
                    <img class="img-fluid" src="{% static 'imgs/logo-03.svg' %}" alt="">
                </div>
                <div class="col"></div>
                <div class="col-auto text-center m-0 p-0" style="word-wrap: unset">All rights reserved 2021 &copy;</div>
            </div>
        </div>
    </div>
</div>
<script src="{% fullstatic 'js/jquery-3.3.1.js' %}"></script>
<script src="{% fullstatic 'js/jquery-ui.js' %}"></script>
<script src="{% fullstatic 'js/bootstrap.min.js' %}"></script>
<script src="{% fullstatic 'js/script.js' %}"></script>
{#{% include 'google_analytics.html' %}#}
</body>
</html>

templates/authors_list.html
{% extends "header_footer.html" %}


{% block body %}
    <div class="container">
        <div class="row">
            {% for author in authors %}
                {% include 'authors_list_item.html' with author=author %}
            {% endfor %}

        </div>

        {% include 'pager.html' %}
    </div>
{% endblock %}

templates/authors_list_item.html
{% load fullurl %}
{% if author %}

    <div class="col-12 my-2">
        <a href="{% url 'Company:detail' author.id %}" class="btn w-100 text-left text-dark">

            <div class="card w-100 shadow-sm" style="overflow: hidden;">
                <div class="row">

                    <div class="col-3" >
{#                        <img class="img-fluid" src="{% fullstatic 'imgs/logo_only.png' %}" alt="">#}
                        <div class="w-100 card-image" style="background: url('{{ author.url }}') no-repeat"></div>
                    </div>

                    <div class="col-8 p-3">
                        <div class="h1">{{ author.name }}</div>
                        <div style="white-space: normal;" class="w-100 mt-2 text-secondary">{{ author.description }}</div>
                    </div>
                </div>
            </div>
        </a>
    </div>


{% endif %}

templates/books_list_item.html
{% load fullurl %}
{% if product %}

<div class="col-3">
    <div class="card text-center">
        <img class="card-img-top" src="{% fullstatic 'imgs/img-12-bg.png' %}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="{% url 'Products:detail' product.id %}" class="btn btn-outline-info">Detail</a>
        </div>
    </div>
</div>
{% endif %}

templates/company_detail.html
{% extends 'header_footer.html' %}
{% load fullurl %}


{% block body %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-12">
                {#                <img class="img-fluid" src="{% url 'media' summary.image.url %}" alt="">#}
                <div class="w-100 card-image"
                     style="background: url('{% url 'media' company.image.url %}'); background-size: 100% !important;"></div>
            </div>

            <div class="col-12 p-3">
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col">

                        <div class="h1 text-center">{{ company.name }}</div>

                        <div class="mt-2 text-secondary">{{ company.description }}</div>
                    </div>
                    <div class="col-2"></div>
                </div>
            </div>

        </div>
    </div>


    <br>
    <br>
    <br>
    <br>
    <div class="row">
        {% for product in products %}
                {% include 'books_list_item.html' with product=product %}
            {% endfor %}
    </div>

{% endblock %}

templates/header_footer.html
{% extends "abstruct_header_footer.html" %}
{% load fullurl %}

{% block full_body %}
    <div class=" bg-light w-100 text-center">

        <div class="container">
            <div class="row">
                <div class="col"></div>

                <div class="col-6 col-sm-8 search-row pt-3">
                    {#                action="{% fullurl 'search' %}"#}
                    <form class="search-form">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <button class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></button>
                            </div>
                            <input name="q" type="text" class="form-control" placeholder="بحث"
                                   value="{{ q }}"
                                   aria-label="Username"
                                   aria-describedby="basic-addon1">
                        </div>

                    </form>
                </div>
                <div class="col"></div>
            </div>
        </div>
    </div>

    {% block body %}

    {% endblock %}




{% endblock %}

templates/home.html
{% extends 'abstruct_header_footer.html' %}
{% load fullurl %}
{% load static %}

{% load i18n %}
{% block full_body %}
<div class="banner" style="">
    <div class="background">


    </div>
    <div class="over"></div>

    <div class="container-fluid text-start">
        <div class="row">

            <div class="col-12 p-5">
                <img class="img-fluid mt-4" src="{% fullstatic 'imgs/logo-02.svg' %}" alt="">
            </div>
        </div>
    </div>
</div>
<div class="row agencies-banner" style="font-size:1.2em; overflow:unset">

    <!--    <img class="img-fluid w-100" src="{% fullstatic 'imgs/tools1.jpeg' %}" alt="">-->
    <div class="over"></div>
    <div class="smoother"></div>
    <div class="content">

        <div class="row">
            <div class="col-12">

                <h1><strong>{% trans 'Agencies' %}</strong></h1>
            </div>
            <div class="col-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col order-12  order-md-1 text-justify py-3" style="direction: rtl;">
                            {% blocktrans %}
                            More than just numbers, what truly defines Tramontina is the constant effort to make
                            people´s lives better. The small iron mill founded by Valentin and Elisa Tramontina in 1911
                            in southern Brazil was the beginning of a group that now encompasses 10 manufacturing units
                            and has kept the century-old tradition of delighting people with simple gestures.
                            {% endblocktrans %}
                            <br>
                            <a class="btn btn-primary" href="{% url 'Company:detail' 1 %}"> {% trans 'Show Products' %}</a>
                        </div>
                        <div class="col-12 col-md-3 order-1  order-md-12">
                            <a href="#">

                                <img class="img-fluid img-thumbnail shadow"
                                     src="{% fullstatic 'imgs/foto_t_store_casashopping_rj_br.jpeg' %}"
                                     alt="">

                            </a>
                        </div>
                    </div>

                    <hr>
                    <div class="row mt-2">

                        <div class="col-12 col-md-3 order-1">
                            <a href="#">
                                <img class="img-fluid img-thumbnail shadow" src="{% fullstatic 'imgs/astra.png' %}"
                                     alt="">
                            </a>
                        </div>
                        <div class="col order-12 text-justify  py-3" style="direction: rtl;">
                            {% blocktrans %}
                            Astra , founded in 1957, in the city of Jundiaí - 60km from the capital of São Paulo - is a
                            multi -specialized company that creates and sells products and solutions for people's daily
                            lives.
                            It has a varied portfolio, composed of items aimed at construction , ranging from the
                            foundation of the work to the finish, from the technical item to the decoration:
                            {% endblocktrans %}
                            <br>
                            <a class="btn btn-primary" href="{% url 'Company:detail' 2 %}"> {% trans 'Show Products' %}</a>
                        </div>
                    </div>
                    <hr>
                    <div class="row mt-2">
                        <div class="col order-12 order-md-1 text-justify  py-3" style="direction: rtl;">
                            {% blocktrans %}
                            Canbond develops and manufactures high grade, premium, affordable cements and adhesives for
                            the international marketplace. Our creed, ‘Bonding Our World, Together' incorporates the
                            highest regard for our client relationships, technical product quality, and competitive
                            confidence.
                            {% endblocktrans %}
                            <br>
                            <a class="btn btn-primary" href="{% url 'Company:detail' 3 %}"> {% trans 'Show Products' %}</a>
                        </div>
                        <div class="col-12 col-md-3 order-1 order-md-12">
                            <a href="#">
                                <img class="img-fluid img-thumbnail shadow"
                                     src="{% fullstatic 'imgs/canbond.jpeg' %}"
                                     alt="">
                            </a>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="container text-dark pt-2 text-center">
    <div class="row pt-5">
        <div class="col-12">
            <p class="fa-3x text-primary">{% trans 'Products' %}</p>
        </div>
        {% for product in products %}
        <div class="col-12 col-lg-3 col-md-6 mb-2">
            <div class="card pt-2 fa-x2">
                <div class="w-100 card-image" style="background: url('{{ product.url }}') no-repeat"></div>
                {% comment %} <img class="card-img-top" src="{% fullstatic 'imgs/img-9-bg.png' %}" alt="Card image cap"> {% endcomment %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <a href="{% url 'Products:detail' product.id %}" class="btn btn-outline-info">{% trans 'View' %}</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-12 text-center mt-5">
        <a href="{% url 'Home:library' %}" class="btn btn-outline-info">{% trans 'All Products' %}</a>
    </div>
    
</div>


<div class="container text-dark pt-2 text-center fa-xs" dir='rtl'>
    <div class="row pt-5">
        <div class="col-12">
            <p class="fa-3x text-primary">{% trans 'Aburgaya Group' %}</p>
        </div>
        <div class="col-12 fa-2x">
            {% blocktrans %}
            Aburgaya Group, the exclusive agent of the Brazilian Tramontina company in Libya, offers you the original products that include: <br/>
            Housewares -
            Hand tools -
            agricultural tools -
            Celestial Sinks <br/>
            We represent the Brazilian company through our exclusive agency in Libya for 20 years <br/>
            
            <br/>
            To inquire about <strong>Housewares</strong> you can us in 
            Misurata roundabout Fakarneh near the round of Alskirat.
            Or call the numbers:
            0910339888 -
            0920339888
            <br/>
            <br/>
            To inquire about <strong>(building materials, agricultural tools, workshop equipment and kitchen sinks)</strong> you can visit us at our headquarters located in Misurata - Al-Majmadat Street - after Omar Ibn Al-Khattab Mosque, 250 meters towards Al-Taqeel.
            Or call the two numbers:
            0915108133 -
            0927108133
            {% endblocktrans %}
        </div>
    </div>
</div>


<!--</div>-->


<br>
<br>


<div class="contact-us text-primary"
     style="">
    <div class="bg"></div>
    <div class="container">
        <div class="row fa-2x">
            <div class="col-12 text-center mt-4">
                <div class="h1">{% trans 'Contact with us' %}:</div>
            </div>
        </div>
        <div class="row mx-0 mx-md-5">

            <div class="col-12 col-md-5 mx-auto">
                <p class="">
                    <h4><i class="fa fa-home"></i> {% trans 'Housewares' %}</h4>
                </p>
                <p class="">
                    <span class="fa fa-phone"></span> <a class="btn text-primary" href="tel:0910339888">0910339888</a> - <a class="btn text-primary" href="tel:0920339888">0920339888</a>
                </p>
                <p class="">
                    <span class="fa fa-map-marker-alt"></span> <a class="btn text-primary">{% trans 'Roundabout Fakarneh - Misurata - Libya' %}</a>
                </p>
                <p class="">
                    <span class="fa fa-envelope"></span> <a href="mailto:sales@aburgayagroup.com" class="btn text-primary">sales@aburgayagroup.com</a>
                </p>

            </div>
            <div class="col-12 col-md-5">
                <p class="">
                    <h4><i class="fa fa-home"></i> {% trans 'Building materials and agricultural tools' %}</p></h4>
                <p class="">
                    <span class="fa fa-phone"></span> <a class="btn text-primary" href="tel:0915108133">0915108133</a> - <a class="btn text-primary" href="tel:0927108133">0927108133</a>
                </p>
                <p class="">
                    <span class="fa fa-map-marker-alt"></span> <a class="btn text-primary">{% trans 'Almujamadat Street - Misurata - Libya' %}</a>
                </p>
                <p class="">
                    <span class="fa fa-envelope"></span> <a href="mailto:sales2@aburgayagroup.com" class="btn text-primary">sales2@aburgayagroup.com</a>
                </p>
            </div>


        </div>
    </div>

</div>


{% endblock %}

templates/library.html
{% extends 'abstruct_header_footer.html' %}
{% load fullurl %}
{% load static %}
{% load i18n %}

{% block full_body %}
    <div class=" bg-dark banner rounded">
        <div class="background">
            <img class="img-fluid" src="{% fullstatic 'imgs/img-10.jpeg' %}" alt="">
        </div>
        <div class="over"></div>

        <div class="container">
            <div class="col-12 mt-5">
                <img class="img-fluid w-50" src="{% fullstatic 'imgs/logo-03.svg' %}"
                     alt="Effective Readers">
            </div>
            <div class="row">
                <div class="col"></div>

                <div class="col-6 col-sm-8 search-row pt-3">
                    
                    <form class="search-form" action="{% url 'Products:home' %}">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <button class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></button>
                            </div>
                            <input name="q" type="text" class="form-control" placeholder="{% trans 'Search' %}"
                                   aria-label="Username"
                                   aria-describedby="basic-addon1">
                        </div>

                    </form>
                </div>
                <div class="col"></div>
            </div>
        </div>
    </div>

    <div class="container text-dark pt-2">
        <div class="row">
            {% for category in categories %}

                <div class="col-auto p-2 border-0 rounded m-2">
                    <a href="#" class="btn btn-light">
                        {{ category.name }}
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>


    <div class="container mt-4">

        <div class="h2">{% trans 'Newest' %}</div>
        <div class="row text-center">
            {% for book in products %}

                <div class="col-3 p-2">
                    <a href="{% url 'Products:detail' book.id %}" class="btn w-100 p-0">
                        <div class="card border p-3">
                            <div class="w-100 card-image" style="background: url('{{ book.url }}') no-repeat">
                            </div>
                            <hr>
                            <div class="h4 text-dark">{{ book.name }}</div>
                            <p class="text-muted">{{ book.company.name }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>






    <div class="container mt-4">

        <div class="h2">{% trans 'By company' %}</div>
        <div class="row text-center">

            {% for company in companies %}
                <div class="col-2">
                    <a href="{% url 'Company:detail' company.id %}" class="btn p-0 w-100">
                        <div class="card border p-3 w-100">
                            <div class="w-100 card-image" style="background: url('{{ company.url }}') no-repeat"></div>
                            <hr>
                            <div class="h6 text-dark">{{ company.name }}</div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>


{% endblock %}

templates/pager.html
{% if page_obj.paginator.num_pages > 1 %}

    <div class="row mt-3">
        <div class="col"></div>
        <div class="col-auto">
            <div class="col-12 text-center">
                <nav aria-label="Page navigation ">
                    <ul class="pagination pagination-lg">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link" href="{% if  page_obj.has_previous %}
                                    ?page={{ page_obj.previous_page_number }}
                        {% else %}#{% endif %}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        </li>

                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link" href="{% if page_obj.has_next %}
                ?page={{ page_obj.next_page_number }}
                {% else %}# {% endif %}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endif %}

templates/product_list.html
{% extends 'header_footer.html' %}
{% load fullurl %}

{% block body %}
    <div class="container">
        <div class="row pt-5">
            {% for product in products %}
                {% include 'books_list_item.html' with product=product %}
            {% endfor %}
        </div>
        {% include 'pager.html' %}
    </div>
{% endblock %}

templates/summaries_list_item.html
{% load fullurl %}
{% if summary %}

    <div class="col-12 my-2">
        <a href="{% url 'Summaries:detail' summary.id %}" class="btn w-100 text-left text-dark">

            <div class="card w-100 shadow-sm" style="overflow: hidden;">
                <div class="row">

                    <div class="col-2" >
{#                        <img class="img-fluid" src="{% fullstatic 'imgs/logo_only.png' %}" alt="">#}
                        <div class="card-image" style="background: url('{% url "media" summary.icon.url %}') no-repeat; height: 100px;"></div>
                    </div>

                    <div class="col-8 p-3">
                        <div class="h1">{{ summary.title }}</div>
                        <div style="white-space: normal;" class="w-100 mt-2 text-secondary">{{ summary.body|slice:"0:100" }}</div>
                    </div>
                </div>
            </div>
        </a>
    </div>


{% endif %}